### ISSUE TITLE
ladna strona

### ISSUE THREAD

**Issue by arekbee** [bnbsystems/aopera_website#1]
https://aoperat.pl/
Tekst

**Comment by arekbee** [comment]
![image](https://user-images.githubusercontent.com/961862/135633468-33575f96-9b07-4cd3-b1bc-fbb23bb2ef27.png)

**Comment by arekbee** [comment]
![image](https://user-images.githubusercontent.com/961862/137576572-04c310a0-6d83-4f6b-9542-4a7351ee5b60.png)

**Comment by arekbee** [comment]
Dodac informacje 
* jak dziala platforma
* odnosnik gdzie mozna znalez szoenie jak obslugiwac szklenie (Aktualnosci)
![image](https://user-images.githubusercontent.com/961862/137576588-76903f6a-9e61-4663-959c-547af53a1525.png)

**Comment by marcin-flad** [comment]
1. Jak działa Netlify 
Netlify zapewnia możliwość hostowania statycznych stron internetowych. Strona jest 
budowana na podstawie repozytorium na GitHub co pozwala na automatyzację deployu 
strony po wprowadzeniu zmian. Netlify pre-renderuje wszystkie strony do statycznego 
HTML na podstawie kodu źródłowego w repozytorium Git. Zamiast ładowania strony przy 
każdej wizycie, z najbliższego serwera zostaje przesłana wstępnie załadowana/zbudowana
strona co znacząco wpływa na poprawę szybkości.

2. Czym jest Netlify CMS
Netlify CMS to system zarządzania treścią oparty o platformę Netlify (jest to opcja 
standardowa i pożądana, ale da się to ominąć, można hostować też np. na AWS). Umożliwia 
tworzenie stron z wykorzystaniem technologii Hugo lub Gatsby. Netlify CMS jest 
stworzone w architekturze Headless CMS. Wykorzystuje stos technologiczny JamStack (J 
– JS, A – API, M – Markdown).

3. Czym jest Headless CMS?
Klasyczny CMS jest systemem monolitycznym zawierającym komplet funkcjonalności 
potrzebnych do zarządzenia treścią. Przykładem klasycznego CMS jest WordPress, w 
którego architekturę wchodzą: baza danych do przechowywania treści, panel administratora 
do zarządzania treścią i wyglądem oraz frontend, który prezentuje treści użytkownikowi. 
Frontend jest tak zwaną głowa systemu, której Headless CMS pozwala się jej „pozbyć”. W 
tym aspekcie nazwa jest nieco myląca bo pozwala nie tyle pozbyć się głowy, co 
odseparować ją od reszty i dać możliwość podmianki na inną w razie potrzeby. Headless 
CMS pomaga zbudować API dostarczające surową treść (raw content), które może zostać 
wykorzystane do wyświetlenia treści zarówno na stronie internetowej jak i w aplikacji 
mobilnej. Headless CMS spełnia rolę backendu (API + repozytorium na treści), który 
można łatwo łączyć platformą Netlify i narzędziami takimi jak Gatsby oparte na React, 
Gridsome oparte na Vue czy też Hugo oparte o język Go.

4. Wady i zalety Headless CMS

Zalety:
• Programista ma dużą swobodę w tworzeniu warstwy wizualne i możliwość 
zmiany z jednej technologii na drugą w dowolnym momencie, warstwę wizualną 
trzeba wtedy stworzyć odnowa ale API i treści (wszystkie artykuły, regulamin, 
opis czym zajmuje się firmy, jak działa produkt, FAQ) zostają. Może się to 
przekładać na lepsze doświadczenia/wrażenia użytkownika podczas używania 
strony.
• Osoba odpowiedzialna za zarządzanie treścią podczas jej zmiany nie ingeruje w 
wygląd strony, zarządza tylko tekstem i zdjęciami, które będą wyświetlone w 
przygotowanych do tego miejscach przygotowanych przez programistę.
• Istnieje możliwość współdzielenia treści przez wiele stron internetowych.

Wady:
• Brak podglądu publikowanej treści dla osoby odpowiedzialnej za zarządzanie 
treścią, którą zapewniają tradycyjne CMS’y.
• Konieczność polegania na developerach, którzy odpowiedzialni są za 
dostarczanie API do publikowania treści. Jeśli trzeba dodać nową stronę, 
programista musi zająć się jej wyglądem, później stworzyć API do 
modyfikowania treści, żeby osoba zarządzająca mogła ją modyfikować. 
Headless CMS nie daje możliwości tworzenia strony bez udziału programisty 
jak wypadku Joomli czy WordPressa
• Większy koszt czasu poświęconego na przygotowanie i rozwój strony, przez 
pozbycie się gotowej warstwy wizualnej i panelu zarządzania

5. Wady i zalety Netlify CMS
Zalety:
• Open-source, serverless, headless
• Nie wymaga dodatkowej bazy danych, bo wykorzystuje GitHuba
• Łatwy start - gotowy starter o nazwie Kaldi do Gatsby JS, który można 
zmodyfikować zamiast tworzyć nowy szablon i wiele innych starterów opartych 
o różne technologie 
• Duża swoboda modyfikacji
Wady:
• Każda zmiana treści to nowy build, użytkownicy zobaczą je dopiero po jego 
wykonaniu, brak możliwości wprowadzania zmian w czasie rzeczywistym, co 
jest niewygodne przy bardzo częstej zmianie treści
• Duże zaangażowanie developera w projekt, tworzenie

**Comment by arekbee** [comment]
https://github.com/bnbsystems/aoperat_frontend/blob/master/aoperat_website_requirements.pdf

**Comment by arekbee** [comment]
Template https://gatsby-netlify-cms.netlify.app/

**Comment by arekbee** [comment]
link https://peaceful-meerkat-940447.netlify.app/

**Comment by arekbee** [comment]
grupa na FB https://www.facebook.com/groups/aoperat/

**Comment by arekbee** [comment]
vimeo https://vimeo.com/user161246910
